require('dotenv').config();
const http=require('http'), path=require('path'), express=require('express'), session=require('express-session'), MongoStore=require('connect-mongo'), helmet=require('helmet');
const {Server}=require('socket.io');
const {connectDatabase}=require('./src/config/database');
const {createContext}=require('./src/config/context');
const {createAuthRouter}=require('./src/routes/auth');
const {createApiRouter}=require('./src/routes/api');
const {createAdminRouter}=require('./src/routes/admin');
const {attachSocketServer}=require('./src/socket');
const PORT=process.env.PORT||3000;
(async()=>{const db=await connectDatabase(); const app=express(); const server=http.createServer(app); const io=new Server(server,{cors:{origin:'*'},pingTimeout:30000,pingInterval:12000});
app.set('trust proxy',1); app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false})); app.use(express.json({limit:'1mb'})); app.use(express.urlencoded({extended:true}));
const sess={secret:process.env.SESSION_SECRET||'dev_secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:1000*60*60*24*30}}; if(db.enabled&&process.env.MONGODB_URI)sess.store=MongoStore.create({mongoUrl:process.env.MONGODB_URI,ttl:60*60*24*30}); app.use(session(sess));
app.use((req,res,next)=>{if(req.path==='/'||req.path.endsWith('.html')||req.path.endsWith('.js')||req.path.endsWith('.css')){res.setHeader('Cache-Control','no-store');res.setHeader('Pragma','no-cache');res.setHeader('Expires','0')}next()});
app.use(express.static(path.join(__dirname,'public'),{etag:false,maxAge:0})); const ctx=createContext({io,db}); app.use('/api/auth',createAuthRouter(ctx)); app.use('/api/admin',createAdminRouter(ctx)); app.use('/api',createApiRouter(ctx)); attachSocketServer(io,ctx);
app.get('/health',(req,res)=>res.json({ok:true,app:'VOID MAFIA',version:'16.0.0-platform',mongodb:db.enabled?'connected':'memory',rooms:ctx.rooms.size,online:ctx.onlineUsers.size,uptime:process.uptime()}));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html'))); server.listen(PORT,()=>console.log(`VOID MAFIA v16 running on ${PORT}; MongoDB: ${db.enabled?'connected':'memory'}`));})().catch(e=>{console.error(e);process.exit(1)});
