const express=require("express"); const {User,Clan}=require("../models"); const {ROLES,DEFAULT_SETTINGS}=require("../gameEngine"); const {publicUser}=require("./auth");
const safe=(v,n=60)=>String(v||"").trim().replace(/\s+/g," ").slice(0,n); const cid=()=>`clan_${Date.now()}_${Math.floor(Math.random()*10000)}`;
function createApiRouter(ctx){const r=express.Router();
 r.get("/health",(req,res)=>res.json({ok:true,version:"17.0.0",mongodb:ctx.dbEnabled,rooms:ctx.rooms.size,uptime:process.uptime()}));
 r.get("/webrtc",(req,res)=>res.json({ok:true,iceServers:ctx.webrtc.iceServers})); r.get("/roles",(req,res)=>res.json({ok:true,roles:ROLES,defaultSettings:DEFAULT_SETTINGS}));
 r.get("/rooms",(req,res)=>res.json({ok:true,rooms:[...ctx.rooms.values()].map(x=>({id:x.id,name:x.name,phase:x.phase,hostName:x.hostName,players:x.players.length,maxPlayers:x.settings.maxPlayers,language:x.settings.language}))}));
 r.get("/rooms/:id",(req,res)=>{const room=ctx.rooms.get(String(req.params.id)); if(!room)return res.status(404).json({ok:false,error:"Room not found"}); res.json({ok:true,room:ctx.engine.publicRoom(room,Number(req.query.userId||0))})});
 r.get("/users/:id",async(req,res)=>{const u=await User.findOne({userId:Number(req.params.id)}).lean(); if(!u)return res.status(404).json({ok:false,error:"User not found"}); res.json({ok:true,user:publicUser(u)})});
 r.get("/leaderboard",async(req,res)=>res.json({ok:true,users:(await User.find({}).sort({"stats.xp":-1,"stats.wins":-1}).limit(100).lean()).map(publicUser)}));
 r.get("/clans",async(req,res)=>res.json({ok:true,clans:await Clan.find({}).sort({level:-1,power:-1,xp:-1}).limit(100).lean()}));
 r.post("/clans",async(req,res)=>{try{const u=await User.findOne({userId:Number(req.body.user?.userId)}); if(!u)throw Error("User not found"); if(u.clanId)throw Error("You already have a clan"); const name=safe(req.body.name,32), tag=safe(req.body.tag,8).toUpperCase(); if(!name)throw Error("Clan name required"); const c=await Clan.create({clanId:cid(),name,tag,emblem:u.avatar,ownerUserId:u.userId,ownerName:u.nickname,members:[{userId:u.userId,nickname:u.nickname,avatar:u.avatar,role:"owner"}]}); u.clanId=c.clanId; await u.save(); res.json({ok:true,clan:c})}catch(e){res.status(400).json({ok:false,error:e.message})}});
 r.post("/clans/:id/join",async(req,res)=>{try{const u=await User.findOne({userId:Number(req.body.user?.userId)}), c=await Clan.findOne({clanId:String(req.params.id)}); if(!u||!c)throw Error("Not found"); if(!c.members.find(m=>Number(m.userId)===Number(u.userId)))c.members.push({userId:u.userId,nickname:u.nickname,avatar:u.avatar}); u.clanId=c.clanId; await u.save(); await c.save(); res.json({ok:true,clan:c})}catch(e){res.status(400).json({ok:false,error:e.message})}});
 r.get("/store",(req,res)=>res.json({ok:true,items:[{key:"neonFrame",title:"Neon Profile Frame",price:150,description:"Vaporwave profile frame"},{key:"voidBadge",title:"VOID Badge",price:100,description:"Cosmetic badge"},{key:"hostStyle",title:"Host Table Style",price:250,description:"Custom hosted room style"}]}));
 return r}
module.exports={createApiRouter};
