const express=require("express"), bcrypt=require("bcryptjs"), nodemailer=require("nodemailer");
const {User,Counter}=require("../models");
const clean=v=>String(v||"Player").trim().replace(/\s+/g," ").slice(0,32)||"Player";
const email=v=>String(v||"").trim().toLowerCase(); const avatar=v=>String(v||"◆").trim().slice(0,4)||"◆";
async function nextId(){const c=await Counter.findOneAndUpdate({key:"userId"},{$setOnInsert:{value:0},$inc:{value:1}},{new:true,upsert:true});return c.value}
function pub(u){if(!u)return null; const o=typeof u.toObject==="function"?u.toObject():u; return {userId:o.userId,nickname:o.nickname,email:o.email||"",avatar:o.avatar||"◆",clanId:o.clanId||"",coins:o.coins||0,crystals:o.crystals||0,stats:o.stats||{},inventory:o.inventory||[]}}
async function welcome(to,nick){ if(!process.env.SMTP_HOST)return; const tr=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:false,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}); await tr.sendMail({from:process.env.MAIL_FROM||process.env.SMTP_USER,to,subject:"Welcome to VOID MAFIA",text:`Welcome, ${nick}.`}); }
function createAuthRouter(){const r=express.Router();
 r.get("/me",async(req,res)=>{const id=Number(req.session.userId||0); if(!id)return res.json({ok:true,user:null}); res.json({ok:true,user:pub(await User.findOne({userId:id}).lean())});});
 r.post("/guest",async(req,res)=>{try{const u=await User.create({userId:await nextId(),nickname:clean(req.body.nickname),avatar:avatar(req.body.avatar)}); req.session.userId=u.userId; res.json({ok:true,user:pub(u)});}catch(e){res.status(400).json({ok:false,error:e.message})}});
 r.post("/register",async(req,res)=>{try{const em=email(req.body.email), pass=String(req.body.password||""); if(!em.includes("@"))throw Error("Email is invalid"); if(pass.length<6)throw Error("Password must be 6+ chars"); if(await User.findOne({email:em}))throw Error("Email already registered"); const u=await User.create({userId:await nextId(),email:em,passwordHash:await bcrypt.hash(pass,10),nickname:clean(req.body.nickname),avatar:avatar(req.body.avatar)}); welcome(em,u.nickname).catch(()=>{}); req.session.userId=u.userId; res.json({ok:true,user:pub(u)});}catch(e){res.status(400).json({ok:false,error:e.message})}});
 r.post("/login",async(req,res)=>{try{const u=await User.findOne({email:email(req.body.email)}); if(!u||!await bcrypt.compare(String(req.body.password||""),u.passwordHash))throw Error("Invalid email or password"); u.lastLoginAt=new Date(); await u.save(); req.session.userId=u.userId; res.json({ok:true,user:pub(u)});}catch(e){res.status(400).json({ok:false,error:e.message})}});
 r.put("/me",async(req,res)=>{try{const id=Number(req.session.userId||req.body.userId||0); if(!id)throw Error("Auth required"); const u=await User.findOne({userId:id}); if(!u)throw Error("User not found"); u.nickname=clean(req.body.nickname||u.nickname); u.avatar=avatar(req.body.avatar||u.avatar); await u.save(); res.json({ok:true,user:pub(u)});}catch(e){res.status(400).json({ok:false,error:e.message})}});
 r.post("/logout",(req,res)=>req.session.destroy(()=>res.json({ok:true}))); return r}
module.exports={createAuthRouter,publicUser:pub};
