const bcrypt=require('bcryptjs'); const {safeText,publicUser,rankFromXp}=require('../utils/text');
async function nextUserId(ctx){if(ctx.db.enabled){const C=ctx.db.models.Counter; const start=Number(process.env.USER_ID_START||1); const d=await C.findOneAndUpdate({key:'userId'},{$setOnInsert:{value:start-1},$inc:{value:1}},{upsert:true,new:true}); return d.value} return ctx.memory.nextUserId++}
async function findUserById(ctx,id){id=Number(id); if(ctx.db.enabled)return publicUser(await ctx.db.models.User.findOne({userId:id})); return publicUser(ctx.memory.users.get(id))}
async function getOrCreateGuest(ctx,p={}){if(p.userId){const ex=await findUserById(ctx,p.userId); if(ex)return updateProfile(ctx,p.userId,p)} const userId=await nextUserId(ctx); const user={userId,nickname:safeText(p.nickname||`Player${userId}`,32),avatar:safeText(p.avatar||'◆',6),country:'GE',isAdmin:ctx.security.adminIds.includes(String(userId)),stats:{coins:100,rating:5,xp:0},inventory:{walkieTalkie:true,roomNames:true}}; if(ctx.db.enabled)return publicUser(await ctx.db.models.User.create(user)); ctx.memory.users.set(userId,user); return publicUser(user)}
async function register(ctx,p={}){const email=String(p.email||'').trim().toLowerCase(), password=String(p.password||''); if(!email||password.length<4)throw Error('Email/password არასწორია'); if(ctx.db.enabled){if(await ctx.db.models.User.findOne({email}))throw Error('Email უკვე რეგისტრირებულია'); const userId=await nextUserId(ctx); return publicUser(await ctx.db.models.User.create({userId,email,passwordHash:await bcrypt.hash(password,10),nickname:safeText(p.nickname||email.split('@')[0],32),avatar:'◆',isAdmin:ctx.security.adminIds.includes(String(userId))}))} for(const u of ctx.memory.users.values())if(u.email===email)throw Error('Email უკვე რეგისტრირებულია'); const userId=await nextUserId(ctx); const u={userId,email,passwordHash:await bcrypt.hash(password,10),nickname:safeText(p.nickname||email.split('@')[0],32),avatar:'◆',stats:{coins:100,rating:5,xp:0},inventory:{walkieTalkie:true,roomNames:true}}; ctx.memory.users.set(userId,u); return publicUser(u)}
async function login(ctx,p={}){const email=String(p.email||'').trim().toLowerCase(), password=String(p.password||''); let u=null; if(ctx.db.enabled){u=await ctx.db.models.User.findOne({email}); if(!u||!await bcrypt.compare(password,u.passwordHash||''))throw Error('Email ან პაროლი არასწორია'); u.lastLoginAt=new Date(); await u.save(); return publicUser(u)} for(const x of ctx.memory.users.values())if(x.email===email)u=x; if(!u||!await bcrypt.compare(password,u.passwordHash||''))throw Error('Email ან პაროლი არასწორია'); return publicUser(u)}
async function updateProfile(ctx,id,p={}){if(ctx.db.enabled){const u=await ctx.db.models.User.findOne({userId:Number(id)}); if(!u)throw Error('User not found'); if(p.nickname)u.nickname=safeText(p.nickname,32); if(p.avatar)u.avatar=safeText(p.avatar,6); u.rank=rankFromXp(u.stats?.xp||0); await u.save(); return publicUser(u)} const u=ctx.memory.users.get(Number(id)); if(!u)throw Error('User not found'); if(p.nickname)u.nickname=safeText(p.nickname,32); if(p.avatar)u.avatar=safeText(p.avatar,6); return publicUser(u)}
async function leaderboard(ctx){if(ctx.db.enabled)return (await ctx.db.models.User.find({isBanned:{$ne:true}}).sort({'stats.xp':-1,'stats.rating':-1}).limit(100)).map(publicUser); return [...ctx.memory.users.values()].map(publicUser).sort((a,b)=>(b.stats.xp||0)-(a.stats.xp||0)).slice(0,100)}
async function applyGameResult(ctx,room,winners=[]){const W=new Set(winners.map(String)); for(const p of room.players){if(ctx.db.enabled){const u=await ctx.db.models.User.findOne({userId:Number(p.userId)}); if(!u)continue; const win=W.has(String(p.id)); u.stats.games+=1; win?u.stats.wins+=1:u.stats.losses+=1; if(['mafia','don','yakuza'].includes(p.role))u.stats.mafiaGames+=1; else u.stats.citizenGames+=1; u.stats.xp+=win?30:10; u.stats.coins+=win?15:5; u.rank=rankFromXp(u.stats.xp); u.matchHistory.unshift({roomId:room.id,roomName:room.name,role:p.role,result:win?'win':'loss',playedAt:new Date()}); u.matchHistory=u.matchHistory.slice(0,50); await u.save()}}}
module.exports={getOrCreateGuest,register,login,updateProfile,findUserById,leaderboard,applyGameResult};
