/**
 * The packer and the unpacker agree.
 *
 * These two live in different languages of the project — a build-time .mjs tool
 * and a runtime .ts module — with nothing but a comment between them. A byte out
 * of step does not throw; it draws a plausible, wrong city, and there is no
 * original to compare it against once it is on screen. So the contract is
 * tested by round-tripping real-shaped data through both halves.
 */

import { test } from 'node:test';
import { strict as assert } from 'assert';

import {
  unpackBuildings, unpackRoads, unpackWater, b64ToBytes,
  QUANT_TOLERANCE_M, HEIGHT_TOLERANCE_M,
} from './tbilisiPack.js';
// The same code the committed asset was generated by. Importing it rather than
// restating its layout is the whole point: a test with its own copy of the
// format would agree with itself while both halves drifted.
import { packBuildings, packRoads, packWater, projector, KINDS } from '../../../tools/osmExtract.mjs';

/** A footprint shaped like the ones this actually meets: small, irregular. */
function ring(cx: number, cz: number, n: number, r: number) {
  return Array.from({ length: n }, (_, i) => {
    const a = (i / n) * Math.PI * 2;
    const rr = r * (0.7 + ((i * 37) % 13) / 20);
    return { x: cx + Math.cos(a) * rr, z: cz + Math.sin(a) * rr };
  });
}

test('a building survives the round trip to within a decimetre', () => {
  const src = [
    { pts: ring(0, 0, 4, 8), height: 10.2, kind: 'house' },
    { pts: ring(-120.4, 63.9, 7, 14.5), height: 25.6, kind: 'apartments' },
    { pts: ring(340.5, -288.1, 12, 30), height: 4, kind: 'garage' },
  ];
  const back = unpackBuildings(packBuildings(src));
  assert.equal(back.length, src.length);
  for (let i = 0; i < src.length; i++) {
    assert.equal(back[i]!.pts.length, src[i]!.pts.length, `building ${i} lost corners`);
    assert.ok(Math.abs(back[i]!.height - src[i]!.height) <= HEIGHT_TOLERANCE_M,
      `building ${i} height ${back[i]!.height} vs ${src[i]!.height}`);
    assert.equal(back[i]!.kind, KINDS.indexOf(src[i]!.kind), `building ${i} changed kind`);
    for (let k = 0; k < src[i]!.pts.length; k++) {
      assert.ok(Math.abs(back[i]!.pts[k]!.x - src[i]!.pts[k]!.x) <= QUANT_TOLERANCE_M + 1e-9,
        `building ${i} vertex ${k} moved in x`);
      assert.ok(Math.abs(back[i]!.pts[k]!.z - src[i]!.pts[k]!.z) <= QUANT_TOLERANCE_M + 1e-9,
        `building ${i} vertex ${k} moved in z`);
    }
  }
});

test('roads keep their width and their line', () => {
  const src = [
    { pts: [{ x: 0, z: 0 }, { x: 40, z: 12 }, { x: 90, z: 5 }], width: 6.5 },
    { pts: [{ x: -200, z: 200 }, { x: -180, z: 240 }], width: 2.2 },
  ];
  const back = unpackRoads(packRoads(src));
  assert.equal(back.length, 2);
  for (let i = 0; i < src.length; i++) {
    assert.ok(Math.abs(back[i]!.width - src[i]!.width) <= 0.05, `road ${i} width`);
    for (let k = 0; k < src[i]!.pts.length; k++) {
      assert.ok(Math.abs(back[i]!.pts[k]!.x - src[i]!.pts[k]!.x) <= QUANT_TOLERANCE_M + 1e-9);
      assert.ok(Math.abs(back[i]!.pts[k]!.z - src[i]!.pts[k]!.z) <= QUANT_TOLERANCE_M + 1e-9);
    }
  }
});

test('the whole district fits the range one int16 of decimetres has', () => {
  /*
   * ±3276.7 m. The district is 800 m across, so this is four times what is
   * needed — but a wider bbox is exactly the kind of change somebody makes
   * later without reading the format, and the failure would be buildings
   * wrapping to the far side of the city rather than an error.
   */
  const far = [{ pts: ring(3200, -3200, 4, 20), height: 12, kind: 'yes' }];
  const back = unpackBuildings(packBuildings(far));
  assert.ok(Math.abs(back[0]!.pts[0]!.x - far[0]!.pts[0]!.x) <= QUANT_TOLERANCE_M + 1e-9,
    'a building 3.2 km out came back somewhere else — the format is at its limit');
});

test('a truncated stream stops, rather than inventing a wall', () => {
  // A corrupted asset is not a recoverable state; half a building is worse
  // than one building fewer, because it looks like geometry.
  const full = packBuildings([
    { pts: ring(0, 0, 5, 10), height: 9, kind: 'house' },
    { pts: ring(50, 50, 5, 10), height: 9, kind: 'house' },
  ]);
  const cut = full.slice(0, full.length - 6);
  const back = unpackBuildings(cut);
  assert.equal(back.length, 1, 'the half-read building was emitted anyway');
});

test('base64 decoding is byte-exact, including the high ones', () => {
  // Coordinates are signed, so the stream is full of 0x80–0xff. A decoder that
  // went through a string would mangle exactly those and nothing else.
  const bytes = Uint8Array.from({ length: 256 }, (_, i) => i);
  const b64 = Buffer.from(bytes).toString('base64');
  assert.deepEqual([...b64ToBytes(b64)], [...bytes]);
});

test('the projection puts north up and east right, at the right scale', () => {
  /*
   * The sign convention matters and is invisible once it is wrong: a world
   * mirrored north-to-south still looks like a city, just not like Tbilisi.
   * three.js looks down −z, so north has to be −z for the map to read the way a
   * map does.
   */
  const p = projector(41.6911, 44.8090);
  const north = p(41.7001, 44.8090);   // 0.009° ≈ 1 km north
  const east = p(41.6911, 44.8210);    // 0.012° ≈ 1 km east at this latitude
  assert.ok(north.z < 0, 'north came out as +z — the district is mirrored');
  assert.ok(Math.abs(north.x) < 0.5, 'due north moved in x');
  assert.ok(east.x > 0, 'east came out as −x');
  assert.ok(Math.abs(east.z) < 0.5, 'due east moved in z');
  // A degree of latitude is 111.3 km; 0.009° of it is 1002 m.
  assert.ok(Math.abs(-north.z - 1002) < 15, `north distance ${(-north.z).toFixed(0)} m`);
  // A degree of longitude here is 111.3 × cos(41.69°) ≈ 83.1 km.
  assert.ok(Math.abs(east.x - 997) < 20, `east distance ${east.x.toFixed(0)} m`);
});

test('a river ring survives, including one longer than a byte can count', () => {
  /*
   * The Mtkvari's bank is hundreds of points. Water uses a u16 count for that
   * reason, and the failure if it did not would be a river that closes itself
   * across the middle of the city — geometry, so nothing would throw.
   */
  const ring = Array.from({ length: 400 }, (_, i) => ({
    x: Math.cos(i / 30) * (120 + i * 0.4),
    z: -300 + i * 1.5,
  }));
  const back = unpackWater(packWater([ring]));
  assert.equal(back.length, 1);
  assert.equal(back[0]!.length, 400, 'the ring was truncated — a u8 count would do exactly this');
  for (let k = 0; k < ring.length; k += 37) {
    assert.ok(Math.abs(back[0]![k]!.x - ring[k]!.x) <= QUANT_TOLERANCE_M + 1e-9, `point ${k} x`);
    assert.ok(Math.abs(back[0]![k]!.z - ring[k]!.z) <= QUANT_TOLERANCE_M + 1e-9, `point ${k} z`);
  }
});

// ── The shipped district ─────────────────────────────────────────────────────

test('every shipped footprint is wound the way the extruder assumes', async () => {
  /*
   * The extruder takes the outward normal of edge a→c to be (dz, −dx), which is
   * only outward if the ring is wound with a positive shoelace area in (x, z).
   * A ring wound the other way builds a building inside out: its walls are
   * culled, you see through it to its own back faces, and nothing throws.
   *
   * Checked against the committed asset rather than a fixture, because the
   * asset is what ships and a regenerate is exactly when this would break.
   */
  const { TBILISI_BUILDINGS_B64, TBILISI_STATS } = await import('./tbilisiData.js');
  const list = unpackBuildings(b64ToBytes(TBILISI_BUILDINGS_B64));
  assert.equal(list.length, TBILISI_STATS.buildings, 'the packed count and the stated count disagree');

  let worst = Infinity;
  for (const b of list) {
    let a2 = 0;
    for (let i = 0, j = b.pts.length - 1; i < b.pts.length; j = i++) {
      a2 += b.pts[j]!.x * b.pts[i]!.z - b.pts[i]!.x * b.pts[j]!.z;
    }
    worst = Math.min(worst, a2 / 2);
  }
  assert.ok(worst > 0, `a footprint is wound backwards (signed area ${worst.toFixed(2)} m²)`);
});

test('the wall normals point away from the building, not into it', async () => {
  /*
   * The same property from the other side, and the one that actually matters:
   * take the extruder's normal for each edge and check it leads away from the
   * footprint's centre. Catches a sign error in the normal itself, which the
   * winding test above would not.
   */
  const { TBILISI_BUILDINGS_B64 } = await import('./tbilisiData.js');
  const list = unpackBuildings(b64ToBytes(TBILISI_BUILDINGS_B64));
  let inward = 0, edges = 0;
  for (const b of list) {
    let cx = 0, cz = 0;
    for (const p of b.pts) { cx += p.x; cz += p.z; }
    cx /= b.pts.length; cz /= b.pts.length;
    for (let i = 0; i < b.pts.length; i++) {
      const a = b.pts[i]!, c = b.pts[(i + 1) % b.pts.length]!;
      const dx = c.x - a.x, dz = c.z - a.z;
      const len = Math.hypot(dx, dz);
      if (len < 0.05) continue;
      edges++;
      const nx = dz / len, nz = -dx / len;
      // From the centroid towards the edge's midpoint.
      const mx = (a.x + c.x) / 2 - cx, mz = (a.z + c.z) / 2 - cz;
      if (nx * mx + nz * mz < 0) inward++;
    }
  }
  /*
   * Not zero: a concave plan — a courtyard, an L around a neighbour — genuinely
   * has edges whose outward normal points back past the centroid, and Old Town
   * is full of them. What would mean a sign error is most of them.
   */
  assert.ok(inward / edges < 0.12,
    `${((100 * inward) / edges).toFixed(1)}% of walls face inward — the normal's sign is wrong`);
});

test('every layer stays inside the district — not just the buildings', async () => {
  /*
   * The bug this is written for, and it cost an afternoon.
   *
   * Overpass returns WHOLE ways, not the part inside the bounding box you
   * asked for. Requesting eight hundred metres of Old Town also returns the
   * entire Mtkvari — a polygon four kilometres across — because one bank of it
   * clips the corner. Packed as int16 decimetres that runs past the ±3276 m the
   * format can hold, and the far points are silently CLAMPED onto the limit.
   *
   * Nothing threw. The river folded into a degenerate spike, three's ear
   * clipper quietly returned a tenth of the faces it should have, and the
   * result was a city with no ground and no water under it — which looked like
   * a lighting problem, then like a winding problem, and was neither.
   *
   * The first version of this test checked buildings only, which is exactly how
   * it got through. Every layer, every time.
   */
  const { TBILISI_BUILDINGS_B64, TBILISI_ROADS_B64, TBILISI_WATER_B64 } = await import('./tbilisiData.js');
  const LIMIT = 760;   // the extractor clips at 700

  const far = (pts: { x: number; z: number }[]) =>
    pts.reduce((m, p) => Math.max(m, Math.abs(p.x), Math.abs(p.z)), 0);

  const b = unpackBuildings(b64ToBytes(TBILISI_BUILDINGS_B64));
  const r = unpackRoads(b64ToBytes(TBILISI_ROADS_B64));
  const w = unpackWater(b64ToBytes(TBILISI_WATER_B64));
  assert.ok(b.length > 400 && r.length > 200 && w.length > 0, 'a layer came back empty');

  for (const [name, layer] of [['buildings', b.map(x => x.pts)], ['roads', r.map(x => x.pts)], ['water', w]] as const) {
    const m = Math.max(...layer.map(far));
    assert.ok(m <= LIMIT, `${name} reach ${m.toFixed(0)} m — past the clip, and near the format's own ceiling`);
  }

  /*
   * And nothing sitting exactly on the packing limit, which is what clamping
   * looks like from the other side: a cluster of points all at 3276.7 m.
   */
  for (const [name, layer] of [['buildings', b.map(x => x.pts)], ['roads', r.map(x => x.pts)], ['water', w]] as const) {
    const pinned = layer.flat().filter(p => Math.abs(Math.abs(p.x) - 3276.7) < 0.2 || Math.abs(Math.abs(p.z) - 3276.7) < 0.2);
    assert.equal(pinned.length, 0, `${name}: ${pinned.length} points are pinned to the int16 limit`);
  }

  const maxH = Math.max(...b.map(x => x.height));
  assert.ok(maxH > 8 && maxH < 102, `tallest building is ${maxH.toFixed(1)} m`);
});
