const crypto=require("crypto"); const {User}=require("./models");
const ROLES=[{key:"mafia",label:"Mafia",team:"mafia",hostEditable:true},{key:"don",label:"Don",team:"mafia",hostEditable:true},{key:"doctor",label:"Doctor",team:"citizen",fixed:1},{key:"sheriff",label:"Sheriff",team:"citizen",fixed:1},{key:"detective",label:"Detective",team:"citizen",hostEditable:true},{key:"bodyguard",label:"Bodyguard",team:"citizen",hostEditable:true},{key:"citizen",label:"Citizen",team:"citizen",auto:true}];
const DEFAULT_SETTINGS={maxPlayers:10,language:"Georgian",timers:{roleReveal:12,night:45,day:90,nomination:45,vote:35,lastWords:30},roles:{mafia:1,don:0,doctor:1,sheriff:1,detective:0,bodyguard:0}};
const PHASES=["role_reveal","night","day","nomination","vote","last_words"]; const safe=(v,n=60)=>String(v||"").trim().replace(/\s+/g," ").slice(0,n); const nid=p=>`${p}_${Date.now()}_${crypto.randomBytes(3).toString("hex")}`; const code=()=>String(Math.floor(100000+Math.random()*900000)); const clone=o=>JSON.parse(JSON.stringify(o));
class GameEngine{constructor(ctx){this.ctx=ctx} level(u){return Math.max(1,Math.floor(Number(u?.stats?.xp||0)/100)+1)}
 normalizeSettings(input={}){const s=clone(DEFAULT_SETTINGS); s.maxPlayers=Math.max(4,Math.min(16,Number(input.maxPlayers||s.maxPlayers))); s.language=safe(input.language||s.language,20)||"Georgian"; const t=input.timers||{}; for(const k of ["roleReveal","night","day","nomination","vote","lastWords"])s.timers[k]=Math.max(5,Math.min(300,Number(t[k]||s.timers[k]))); const r=input.roles||{}; s.roles.mafia=Math.max(1,Math.min(6,Number(r.mafia??s.roles.mafia))); s.roles.don=Math.max(0,Math.min(1,Number(r.don??s.roles.don))); s.roles.doctor=1; s.roles.sheriff=1; s.roles.detective=Math.max(0,Math.min(2,Number(r.detective??0))); s.roles.bodyguard=Math.max(0,Math.min(2,Number(r.bodyguard??0))); return this.balance(s)}
 balance(s){let fixed=s.roles.mafia+s.roles.don+1+1+s.roles.detective+s.roles.bodyguard; if(fixed>s.maxPlayers){s.roles.mafia=Math.max(1,s.maxPlayers-4);s.roles.don=0;s.roles.detective=0;s.roles.bodyguard=0} s.roles.doctor=1;s.roles.sheriff=1; s.roles.citizen=Math.max(0,s.maxPlayers-(s.roles.mafia+s.roles.don+s.roles.doctor+s.roles.sheriff+s.roles.detective+s.roles.bodyguard)); return s}
 makePlayer(u,seat){return{id:nid("p"),socketId:"",userId:Number(u.userId),nickname:u.nickname||"Player",avatar:u.avatar||"◆",seat,level:this.level(u),connected:true,alive:true,role:"",team:"",micOn:true,cameraOn:true,speaking:false}}
 createRoom({name,host,settings}){if(!host?.userId)throw Error("Auth required"); let id=code(); while(this.ctx.rooms.has(id))id=code(); const r={id,name:safe(name,40)||"VOID TABLE",phase:"waiting",phaseLabel:"Lobby",day:0,timer:0,hostUserId:Number(host.userId),hostName:host.nickname||"Host",settings:this.normalizeSettings(settings||{}),players:[],spectators:[],chat:[],events:[],votes:{},nominations:[],nightActions:{},gameOver:null,createdAt:Date.now()}; r.players.push(this.makePlayer(host,1)); this.ctx.rooms.set(id,r); this.log(r,`Room created by ${r.hostName}`); this.publishRooms(); return r}
 joinRoom(id,u,socketId,spec=false){const r=this.ctx.rooms.get(String(id)); if(!r)throw Error("Room not found"); let p=r.players.find(x=>x.userId===Number(u.userId)); if(!spec&&p){p.connected=true;p.socketId=socketId;return{room:r,player:p,spectator:false}} if(spec||r.players.length>=r.settings.maxPlayers||r.phase!=="waiting"){const s={socketId,userId:Number(u.userId),nickname:u.nickname,avatar:u.avatar,connected:true}; r.spectators=r.spectators.filter(x=>x.userId!==s.userId); r.spectators.push(s); return{room:r,player:s,spectator:true}} const seat=[...Array(r.settings.maxPlayers)].map((_,i)=>i+1).find(n=>!r.players.some(p=>p.seat===n))||r.players.length+1; p=this.makePlayer(u,seat); p.socketId=socketId; r.players.push(p); this.log(r,`${p.nickname} joined.`); this.publishRooms(); return{room:r,player:p,spectator:false}}
 leave(socketId){const rid=this.ctx.socketRooms.get(socketId), r=rid&&this.ctx.rooms.get(rid); if(!r)return; const p=r.players.find(x=>x.socketId===socketId); if(p&&p.userId===r.hostUserId){this.ctx.io.to(r.id).emit("room:terminated",{roomId:r.id}); this.ctx.rooms.delete(r.id); this.publishRooms(); return} if(p){p.connected=false;p.socketId="";p.speaking=false;this.log(r,`${p.nickname} left.`)} r.spectators=r.spectators.filter(s=>s.socketId!==socketId); this.roomState(r); this.publishRooms()}
 updateSettings(r,s,u){if(!r)throw Error("Room not found"); if(Number(r.hostUserId)!==Number(u))throw Error("Host only"); if(r.phase!=="waiting")throw Error("Lobby only"); r.settings=this.normalizeSettings({...r.settings,...s,timers:{...r.settings.timers,...(s?.timers||{})},roles:{...r.settings.roles,...(s?.roles||{})}}); this.log(r,"Settings updated."); this.roomState(r)}
 start(r,u){if(!r)throw Error("Room not found"); if(Number(r.hostUserId)!==Number(u))throw Error("Host only"); if(r.players.length<4)throw Error("Need 4 players"); this.assign(r); r.phase="role_reveal"; r.phaseLabel="Role Reveal"; r.timer=r.settings.timers.roleReveal; this.log(r,"Game started."); this.roomState(r); this.publishRooms()}
 assign(r){let bag=[]; Object.entries(r.settings.roles).forEach(([role,c])=>{for(let i=0;i<Number(c||0);i++)bag.push(role)}); while(bag.length<r.players.length)bag.push("citizen"); bag.sort(()=>Math.random()-.5); r.players.forEach((p,i)=>{p.role=bag[i]||"citizen";p.team=["mafia","don"].includes(p.role)?"mafia":"citizen";p.alive=true})}
 async nextPhase(r){if(!r||["waiting","ended"].includes(r.phase))return; if(r.phase==="night")this.resolveNight(r); if(r.phase==="vote")this.resolveVote(r); const win=this.checkWin(r); if(win)return this.endGame(r,win); let i=PHASES.indexOf(r.phase), next=PHASES[(i+1)%PHASES.length]; if(next==="night")r.day++; r.phase=next; r.phaseLabel={role_reveal:"Role Reveal",night:"Night",day:"Day",nomination:"Nomination",vote:"Vote",last_words:"Last Words"}[next]; r.timer=r.settings.timers[{role_reveal:"roleReveal",night:"night",day:"day",nomination:"nomination",vote:"vote",last_words:"lastWords"}[next]]||30; r.votes={}; if(next==="nomination")r.nominations=[]; if(next==="night")r.nightActions={}; this.roomState(r)}
 nominate(r,a,targetId){if(r.phase!=="nomination")throw Error("Not nomination phase"); const t=r.players.find(p=>p.id===targetId&&p.alive); if(!a?.alive||!t)throw Error("Invalid target"); if(!r.nominations.some(n=>n.targetId===t.id))r.nominations.push({by:a.id,targetId:t.id}); this.roomState(r); return{ok:true}}
 vote(r,a,targetId){if(r.phase!=="vote")throw Error("Not vote phase"); if(!a?.alive)throw Error("Not alive"); r.votes[a.id]=targetId; this.roomState(r); return{ok:true}}
 action(r,a,p){if(r.phase!=="night")throw Error("Not night phase"); const t=r.players.find(x=>x.id===p.targetId&&x.alive); if(!a?.alive||!t)throw Error("Invalid target"); r.nightActions[a.id]={actorId:a.id,role:a.role,targetId:t.id}; this.roomState(r); return{ok:true}}
 resolveVote(r){const c={}; Object.values(r.votes).forEach(id=>{if(id!=="abstain")c[id]=(c[id]||0)+1}); let top="",max=0,tie=false; Object.entries(c).forEach(([id,n])=>{if(n>max){top=id;max=n;tie=false}else if(n===max)tie=true}); if(top&&!tie){const p=r.players.find(x=>x.id===top); if(p){p.alive=false;this.log(r,`${p.nickname} was voted out.`)}}}
 resolveNight(r){const acts=Object.values(r.nightActions), prot=new Set(acts.filter(a=>["doctor","bodyguard"].includes(a.role)).map(a=>a.targetId)), kill=acts.find(a=>["mafia","don"].includes(a.role))?.targetId; const t=r.players.find(p=>p.id===kill); if(t){ if(prot.has(t.id))this.log(r,`${t.nickname} was saved.`); else {t.alive=false;this.log(r,`${t.nickname} died at night.`)}} acts.filter(a=>["sheriff","detective"].includes(a.role)).forEach(a=>{const ac=r.players.find(p=>p.id===a.actorId), tg=r.players.find(p=>p.id===a.targetId); if(ac?.socketId&&tg)this.ctx.io.to(ac.socketId).emit("private:result",{text:`${tg.nickname}: ${tg.team==="mafia"?"MAFIA TEAM":"NOT MAFIA"}`})})}
 checkWin(r){const alive=r.players.filter(p=>p.alive), m=alive.filter(p=>p.team==="mafia").length, c=alive.length-m; if(m<=0)return{team:"citizen",label:"Citizens win"}; if(m>=c)return{team:"mafia",label:"Mafia wins"}; return null}
 async endGame(r,win){r.phase="ended";r.phaseLabel="Ended";r.gameOver=win;r.timer=0;this.roomState(r);this.publishRooms(); for(const p of r.players){const res=p.team===win.team?"win":"loss"; await User.updateOne({userId:p.userId},{$inc:{"stats.games":1,[`stats.${res}s`]:1,"stats.survived":p.alive?1:0,"stats.mafiaGames":p.team==="mafia"?1:0,"stats.citizenGames":p.team!=="mafia"?1:0,"stats.xp":res==="win"?25:8,coins:res==="win"?10:3},$push:{matchHistory:{$each:[{roomId:r.id,roomName:r.name,role:p.role,team:p.team,result:res,survived:p.alive,playedAt:new Date()}],$position:0,$slice:50}}})}}
 chat(r,s,m,ch="room"){const msg={id:nid("m"),channel:ch,userId:s.userId,seat:s.seat||"",nickname:s.nickname||"Player",message:safe(m,500),at:Date.now()}; if(!msg.message)throw Error("Message empty"); r.chat.push(msg); r.chat=r.chat.slice(-120); return msg}
 log(r,text){r.events.push({id:nid("e"),text,at:Date.now()});r.events=r.events.slice(-120)}
 publicRoom(r,uid){const v=r.players.find(p=>p.userId===Number(uid)); return{id:r.id,name:r.name,phase:r.phase,phaseLabel:r.phaseLabel,day:r.day,timer:r.timer,hostUserId:r.hostUserId,hostName:r.hostName,settings:r.settings,players:r.players.map(p=>({...p,role:v&&(v.id===p.id||r.phase==="ended")?p.role:"",team:v&&(v.id===p.id||r.phase==="ended")?p.team:""})),spectators:r.spectators,chat:r.chat.filter(m=>m.channel==="room"),events:r.events,nominations:r.nominations,votesCount:Object.keys(r.votes||{}).length,alive:r.players.filter(p=>p.alive).length,viewer:{isHost:r.hostUserId===Number(uid),playerId:v?.id||"",seat:v?.seat||"",role:v?.role||"",team:v?.team||"",alive:v?.alive!==false},gameOver:r.gameOver}}
 roomState(r){[...r.players,...r.spectators].forEach(p=>p.socketId&&this.ctx.io.to(p.socketId).emit("room:state",this.publicRoom(r,p.userId)))} publishRooms(){this.ctx.io.emit("rooms:list",[...this.ctx.rooms.values()].map(r=>({id:r.id,name:r.name,phase:r.phase,hostName:r.hostName,players:r.players.length,maxPlayers:r.settings.maxPlayers,language:r.settings.language})))} }
module.exports={GameEngine,ROLES,DEFAULT_SETTINGS};
