const crypto=require("crypto");
const ROLES=[
 {key:"citizen",label:"Citizen",team:"citizen",night:false,desc:"Normal town player."},{key:"mafia",label:"Mafia",team:"mafia",night:true,desc:"Kills at night."},{key:"don",label:"Don",team:"mafia",night:true,desc:"Mafia leader."},{key:"consigliere",label:"Consigliere",team:"mafia",night:true,desc:"Checks roles."},{key:"blackmailer",label:"Blackmailer",team:"mafia",night:true,desc:"Silences a target."},
 {key:"doctor",label:"Doctor",team:"citizen",night:true,desc:"Protects one player."},{key:"sheriff",label:"Sheriff",team:"citizen",night:true,desc:"Checks suspicion."},{key:"detective",label:"Detective",team:"citizen",night:true,desc:"Investigates role."},{key:"bodyguard",label:"Bodyguard",team:"citizen",night:true,desc:"Protects a player."},{key:"journalist",label:"Journalist",team:"citizen",night:true,desc:"Compares players."},{key:"fortune_teller",label:"Fortune Teller",team:"citizen",night:true,desc:"Reveals clues."},
 {key:"serial_killer",label:"Serial Killer",team:"neutral",night:true,desc:"Independent killer."},{key:"maniac",label:"Maniac",team:"neutral",night:true,desc:"Blocks a target."},{key:"jester",label:"Jester",team:"neutral",night:false,desc:"Wins if voted out."},{key:"survivor",label:"Survivor",team:"neutral",night:false,desc:"Survive to win."}
];
const ROLE_MAP=Object.fromEntries(ROLES.map(r=>[r.key,r]));
const DEFAULT_SETTINGS={maxPlayers:10,minPlayers:4,language:"Georgian",privacy:"public",password:"",allowSpectators:true,spectatorChat:true,spectatorAudio:false,preset:"classic",timers:{roleReveal:12,night:45,nightResult:8,day:90,nomination:45,vote:35,lastWords:20},roles:{mafia:1,don:0,consigliere:0,blackmailer:0,doctor:1,sheriff:1,detective:0,bodyguard:0,journalist:0,fortune_teller:0,serial_killer:0,maniac:0,jester:0,survivor:0}};
function safeText(v,max=64){return String(v||"").trim().replace(/\s+/g," ").slice(0,max)} function roomId(){return String(Math.floor(100000+Math.random()*900000))} function shuffle(a){a=[...a]; for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]} return a}
function mergeSettings(input={}){const s=JSON.parse(JSON.stringify(DEFAULT_SETTINGS)); Object.assign(s,input||{}); s.timers=Object.assign({},DEFAULT_SETTINGS.timers,input.timers||{}); s.roles=Object.assign({},DEFAULT_SETTINGS.roles,input.roles||{}); s.maxPlayers=Math.max(4,Math.min(16,Number(s.maxPlayers||10))); s.minPlayers=4; s.roles.doctor=1; s.roles.sheriff=1; s.roles.mafia=Math.max(1,Math.min(6,Number(s.roles.mafia||1))); s.roles.citizen=0; return s}
function applyPreset(name,maxPlayers=10){const s=mergeSettings({maxPlayers}); if(name==="balanced"){s.roles.mafia=maxPlayers>=8?2:1;s.roles.don=maxPlayers>=7?1:0;s.roles.detective=maxPlayers>=8?1:0;s.roles.bodyguard=maxPlayers>=10?1:0}else if(name==="advanced"){s.roles.mafia=maxPlayers>=8?2:1;s.roles.don=1;s.roles.detective=1;s.roles.bodyguard=maxPlayers>=9?1:0;s.roles.serial_killer=maxPlayers>=10?1:0}else if(name==="chaos"){s.roles.mafia=Math.max(1,Math.floor(maxPlayers/4));s.roles.don=maxPlayers>=6?1:0;s.roles.detective=1;s.roles.bodyguard=1;s.roles.serial_killer=maxPlayers>=8?1:0;s.roles.jester=maxPlayers>=7?1:0} s.preset=name; return s}
function createEngine(ctx){
 const publishRooms=()=>ctx.io.emit("rooms:list",Array.from(ctx.rooms.values()).filter(r=>r.privacy==="public").map(roomListItem));
 function emitRoom(room){for(const p of room.players)if(p.socketId)ctx.io.to(p.socketId).emit("room:state",publicRoom(room,p.userId)); for(const s of room.spectators)if(s.socketId)ctx.io.to(s.socketId).emit("room:state",publicRoom(room,s.userId,true)); publishRooms()}
 function log(room,text,type="info"){room.events.push({text,type,at:Date.now()}); if(room.events.length>300)room.events.shift()}
 function makePlayer(u,seat){return {id:crypto.randomUUID(),userId:Number(u.userId),socketId:"",seat,nickname:u.nickname||"Player",avatar:u.avatar||"◆",level:u.level||1,rank:u.rank||"Citizen",clanId:u.clanId||"",role:"",team:"",alive:true,connected:true,ready:false,micOn:true,cameraOn:true,speaking:false,engineMuted:false,silenced:false,lastActive:Date.now()}}
 function createRoom({name,host,settings}){const merged=settings?.preset&&settings.preset!=="custom"?applyPreset(settings.preset,settings.maxPlayers):mergeSettings(settings); const r={id:roomId(),name:safeText(name,40)||"VOID TABLE",hostUserId:Number(host.userId),hostName:host.nickname||"Player",phase:"waiting",day:0,timer:0,settings:merged,privacy:merged.privacy||"public",password:merged.password||"",locked:false,players:[makePlayer(host,1)],spectators:[],chat:[],mafiaChat:[],deadChat:[],spectatorChat:[],events:[],nominations:[],votes:{},nightActions:{},lastEliminatedId:null,gameOver:null,startedAt:null,endedAt:null,createdAt:Date.now()}; ctx.rooms.set(r.id,r); log(r,`${host.nickname} created the room`); return r}
 function nextSeat(r){for(let i=1;i<=r.settings.maxPlayers;i++)if(!r.players.some(p=>p.seat===i))return i; return r.players.length+1}
 function joinRoom(roomId,u,socketId,opts={}){const r=ctx.rooms.get(String(roomId)); if(!r)throw Error("Room not found"); if(r.locked&&Number(u.userId)!==Number(r.hostUserId))throw Error("Room is locked"); if(r.password&&r.password!==opts.password)throw Error("Wrong room password"); if(opts.spectator){if(!r.settings.allowSpectators)throw Error("Spectators disabled"); let sp=r.spectators.find(x=>Number(x.userId)===Number(u.userId)); if(!sp){sp={userId:Number(u.userId),socketId,nickname:u.nickname,avatar:u.avatar||"◆",connected:true}; r.spectators.push(sp)} sp.socketId=socketId;sp.connected=true; log(r,`${u.nickname} joined as spectator`); return {room:r,spectator:true}} let p=r.players.find(x=>Number(x.userId)===Number(u.userId)); if(p){p.socketId=socketId;p.connected=true;p.lastActive=Date.now(); log(r,`${u.nickname} reconnected`); return {room:r,spectator:false}} if(r.phase!=="waiting")throw Error("Game already started"); if(r.players.length>=r.settings.maxPlayers)throw Error("Room is full"); p=makePlayer(u,nextSeat(r)); p.socketId=socketId; r.players.push(p); log(r,`${u.nickname} joined the room`); return {room:r,spectator:false}}
 function leaveBySocket(socketId){const id=ctx.socketRooms.get(socketId),r=id&&ctx.rooms.get(String(id)); if(!r)return null; const p=r.players.find(x=>x.socketId===socketId); if(p){if(Number(p.userId)===Number(r.hostUserId)){terminateRoom(r,"Host left. Room terminated."); return r} p.connected=false;p.socketId="";p.speaking=false;p.micOn=false;p.cameraOn=false;log(r,`${p.nickname} disconnected`)} r.spectators=r.spectators.filter(s=>s.socketId!==socketId); return r}
 function terminateRoom(r,reason="Room terminated"){r.phase="ended";r.timer=0;r.gameOver={winner:"terminated",label:reason};r.endedAt=Date.now();log(r,reason,"danger");emitRoom(r);setTimeout(()=>ctx.rooms.delete(r.id),1500)}
 function updateSettings(r,settings,userId){if(!r)throw Error("Room not found"); if(Number(userId)!==Number(r.hostUserId))throw Error("Host only"); if(r.phase!=="waiting")throw Error("Settings only in lobby"); const m=settings?.preset&&settings.preset!=="custom"?applyPreset(settings.preset,settings.maxPlayers||r.settings.maxPlayers):mergeSettings({...r.settings,...settings}); r.settings=m;r.privacy=m.privacy||"public";r.password=m.password||"";log(r,"Room settings updated");emitRoom(r)}
 function setReady(r,userId,ready){const p=r.players.find(x=>Number(x.userId)===Number(userId)); if(!p)throw Error("Player not found"); p.ready=!!ready;p.lastActive=Date.now();emitRoom(r)}
 function assignRoles(r){const roles=[];for(const [role,count] of Object.entries(r.settings.roles)){if(role==="citizen")continue;for(let i=0;i<Number(count||0);i++)roles.push(role)} while(roles.length<r.players.length)roles.push("citizen"); shuffle(roles).slice(0,r.players.length).forEach((role,i)=>{r.players[i].role=role;r.players[i].team=ROLE_MAP[role]?.team||"citizen";r.players[i].alive=true;r.players[i].silenced=false})}
 function start(r,userId){if(!r)throw Error("Room not found"); if(Number(userId)!==Number(r.hostUserId))throw Error("Host only"); if(r.phase!=="waiting")throw Error("Already started"); if(r.players.length<4)throw Error("Minimum 4 players required"); const ready=r.players.filter(p=>p.ready||Number(p.userId)===Number(r.hostUserId)).length; if(ready<Math.ceil(r.players.length/2))throw Error("Not enough ready players"); assignRoles(r); r.phase="role_reveal";r.timer=r.settings.timers.roleReveal;r.startedAt=Date.now();r.day=0;log(r,"Game started");emitRoom(r)}
 async function nextPhase(r){if(!r||r.phase==="ended"||r.phase==="waiting")return; const win=checkWin(r); if(win)return finishGame(r,win); if(r.phase==="role_reveal"){r.phase="night";r.day=1;r.timer=r.settings.timers.night;r.nightActions={};log(r,"Night started")} else if(r.phase==="night"){resolveNight(r);r.phase="night_result";r.timer=r.settings.timers.nightResult;log(r,"Night result")} else if(r.phase==="night_result"){const w=checkWin(r);if(w)return finishGame(r,w);r.phase="day";r.timer=r.settings.timers.day;r.nominations=[];r.votes={};r.players.forEach(p=>p.silenced=false);log(r,"Day started")} else if(r.phase==="day"){r.phase="nomination";r.timer=r.settings.timers.nomination;log(r,"Nomination started")} else if(r.phase==="nomination"){r.phase="vote";r.timer=r.settings.timers.vote;r.votes={};log(r,"Vote started")} else if(r.phase==="vote"){resolveVote(r);r.phase=r.lastEliminatedId?"last_words":"elimination";r.timer=r.lastEliminatedId?r.settings.timers.lastWords:4} else if(r.phase==="last_words"){r.phase="elimination";r.timer=4} else if(r.phase==="elimination"){const w=checkWin(r);if(w)return finishGame(r,w);r.phase="night";r.day++;r.timer=r.settings.timers.night;r.nightActions={};log(r,"Next night started")} emitRoom(r)}
 function nominate(r,p,targetId){if(!p||!p.alive)throw Error("You cannot nominate"); if(r.phase!=="nomination")throw Error("Not nomination phase"); const t=r.players.find(x=>x.id===targetId&&x.alive); if(!t||t.id===p.id)throw Error("Invalid target"); if(!r.nominations.includes(t.id))r.nominations.push(t.id);log(r,`${p.nickname} nominated ${t.nickname}`);emitRoom(r);return {ok:true}}
 function vote(r,p,targetId){if(!p||!p.alive)throw Error("You cannot vote"); if(r.phase!=="vote")throw Error("Not voting phase"); if(r.votes[p.id])throw Error("Already voted"); if(targetId!=="abstain"&&!r.nominations.includes(targetId))throw Error("Invalid candidate"); r.votes[p.id]=targetId;log(r,`${p.nickname} voted`);emitRoom(r);return {ok:true}}
 function nightAction(r,p,targetId){if(!p||!p.alive)throw Error("You cannot act"); if(r.phase!=="night")throw Error("Not night phase"); const t=r.players.find(x=>x.id===targetId&&x.alive); if(!t)throw Error("Invalid target"); if(!ROLE_MAP[p.role]?.night)throw Error("Your role has no night action"); r.nightActions[p.id]={actorId:p.id,role:p.role,targetId:t.id};log(r,`${p.nickname} selected night action`,"secret"); if(p.role==="sheriff")return {ok:true,result:t.team==="mafia"?"Suspicious":"Not suspicious"}; if(["detective","consigliere"].includes(p.role))return {ok:true,result:`${t.nickname}: ${ROLE_MAP[t.role]?.label||t.role}`}; return {ok:true}}
 function resolveNight(r){const actions=Object.values(r.nightActions),saved=new Set(),guarded=new Set(),kills=[]; actions.forEach(a=>{if(a.role==="doctor")saved.add(a.targetId); if(a.role==="bodyguard")guarded.add(a.targetId)}); const mafia=actions.filter(a=>["mafia","don"].includes(a.role)); if(mafia.length){const c={};mafia.forEach(a=>c[a.targetId]=(c[a.targetId]||0)+1); const target=Object.entries(c).sort((a,b)=>b[1]-a[1])[0]?.[0]; if(target)kills.push({targetId:target,by:"mafia"})} actions.filter(a=>a.role==="serial_killer").forEach(a=>kills.push({targetId:a.targetId,by:"serial killer"})); actions.filter(a=>["blackmailer","maniac"].includes(a.role)).forEach(a=>{const t=r.players.find(p=>p.id===a.targetId); if(t)t.silenced=true}); let killed=0; for(const k of kills){const t=r.players.find(p=>p.id===k.targetId&&p.alive); if(!t)continue; if(saved.has(t.id)||guarded.has(t.id)){log(r,`${t.nickname} was attacked but survived`);continue} t.alive=false;killed++;log(r,`${t.nickname} died at night`)} if(!killed)log(r,"No one died at night")}
 function resolveVote(r){const c={};Object.values(r.votes).forEach(v=>{if(v!=="abstain")c[v]=(c[v]||0)+1}); const s=Object.entries(c).sort((a,b)=>b[1]-a[1]); r.lastEliminatedId=null; if(!s[0]||(s[1]&&s[0][1]===s[1][1]))return log(r,"Vote ended with no elimination"); const p=r.players.find(x=>x.id===s[0][0]); if(p&&p.alive){p.alive=false;r.lastEliminatedId=p.id;log(r,`${p.nickname} was eliminated by vote`); if(p.role==="jester")r.gameOver={winner:"jester",label:`${p.nickname} wins as Jester`}}}
 function checkWin(r){if(r.gameOver?.winner)return r.gameOver.winner; const alive=r.players.filter(p=>p.alive),mafia=alive.filter(p=>p.team==="mafia"),town=alive.filter(p=>p.team==="citizen"),serial=alive.filter(p=>p.role==="serial_killer"); if(serial.length===1&&alive.length===1)return "serial_killer"; if(mafia.length===0&&serial.length===0)return "citizens"; if(mafia.length>=town.length+serial.length)return "mafia"; return null}
 async function finishGame(r,winner){r.phase="ended";r.timer=0;r.endedAt=Date.now();r.gameOver={winner,label:`${winner} win`};log(r,`Game over: ${winner} win`); await updateStats(r,winner).catch(e=>console.error("stats",e.message)); emitRoom(r)}
 async function updateStats(r,winner){if(!ctx.db.enabled)return; const U=ctx.db.models.User,Log=ctx.db.models.RoomLog; for(const p of r.players){const won=(winner==="citizens"&&p.team==="citizen")||(winner==="mafia"&&p.team==="mafia")||(winner==="serial_killer"&&p.role==="serial_killer")||(winner==="jester"&&p.role==="jester"); const inc={"stats.games":1,"stats.xp":won?25:8,"stats.seasonXp":won?25:8}; inc[won?"stats.wins":"stats.losses"]=1; if(p.team==="mafia")inc["stats.mafiaGames"]=1; if(p.team==="citizen")inc["stats.citizenGames"]=1; if(won&&p.team==="mafia")inc["stats.mafiaWins"]=1; if(won&&p.team==="citizen")inc["stats.citizenWins"]=1; await U.updateOne({userId:p.userId},{$inc:inc,$push:{matchHistory:{$each:[{roomId:r.id,roomName:r.name,role:p.role,team:p.team,result:won?"win":"loss",survived:p.alive,winner,playedAt:new Date()}],$position:0,$slice:50}}})} await Log.create({roomId:r.id,roomName:r.name,hostUserId:r.hostUserId,winner,players:r.players,events:r.events,votes:r.votes,startedAt:r.startedAt?new Date(r.startedAt):null,endedAt:new Date()})}
 function chat(r,sender,message,channel="room"){message=safeText(message,300); if(!message)throw Error("Empty message"); const p=r.players.find(x=>Number(x.userId)===Number(sender.userId)); if(channel==="mafia"&&(!p||p.team!=="mafia"||r.phase!=="night"))throw Error("Mafia chat is only for mafia at night"); if(channel==="dead"&&(!p||p.alive))throw Error("Dead chat only"); if(channel==="spectator"&&!r.settings.spectatorChat)throw Error("Spectator chat disabled"); const msg={id:crypto.randomUUID(),channel,userId:sender.userId,seat:p?.seat||"",nickname:sender.nickname||p?.nickname||"Player",message,at:Date.now()}; ({mafia:r.mafiaChat,dead:r.deadChat,spectator:r.spectatorChat,room:r.chat}[channel]||r.chat).push(msg); return msg}
 function roomListItem(r){return {id:r.id,name:r.name,phase:r.phase,hostName:r.hostName,players:r.players.length,maxPlayers:r.settings.maxPlayers,language:r.settings.language,privacy:r.privacy,locked:r.locked,createdAt:r.createdAt}}
 function publicRoom(r,viewerUserId,spectator=false){const v=r.players.find(p=>Number(p.userId)===Number(viewerUserId)); return {id:r.id,name:r.name,hostUserId:r.hostUserId,hostName:r.hostName,phase:r.phase,day:r.day,timer:r.timer,settings:{...r.settings,password:r.password?"******":""},privacy:r.privacy,locked:r.locked,players:r.players.map(p=>({id:p.id,userId:p.userId,socketId:p.socketId,seat:p.seat,nickname:p.nickname,avatar:p.avatar,level:p.level,rank:p.rank,clanId:p.clanId,role:p.userId===viewerUserId||r.phase==="ended"?p.role:"",team:p.userId===viewerUserId||r.phase==="ended"?p.team:"",alive:p.alive,connected:p.connected,ready:p.ready,micOn:p.micOn,cameraOn:p.cameraOn,speaking:p.speaking,engineMuted:p.engineMuted,silenced:p.silenced})),spectators:r.spectators.map(s=>({userId:s.userId,nickname:s.nickname,avatar:s.avatar,connected:s.connected})),nominations:r.nominations,votesCount:Object.keys(r.votes).length,chat:r.chat.slice(-80),mafiaChat:v?.team==="mafia"?r.mafiaChat.slice(-80):[],deadChat:v&&!v.alive?r.deadChat.slice(-80):[],spectatorChat:spectator?r.spectatorChat.slice(-80):[],events:r.events.filter(e=>e.type!=="secret").slice(-80),gameOver:r.gameOver,viewer:{isHost:Number(r.hostUserId)===Number(viewerUserId),spectator,role:v?.role||"",team:v?.team||"",alive:v?.alive??false,ready:v?.ready??false}}}
 return {createRoom,joinRoom,leaveBySocket,terminateRoom,updateSettings,setReady,start,nextPhase,nominate,vote,nightAction,chat,emitRoom,publishRooms,roomState:emitRoom,roomListItem,publicRoom}
}
module.exports={createEngine,ROLES,ROLE_MAP,DEFAULT_SETTINGS};
