const {User}=require("./models");
function attachSocketServer(io,ctx){const user=s=>s.data.user, roomOf=id=>ctx.rooms.get(String(id)), bySocket=(r,id)=>r?.players?.find(p=>p.socketId===id);
io.on("connection",socket=>{
 socket.on("auth",async(p={},cb)=>{try{const u=await User.findOne({userId:Number(p.userId)}).lean(); if(!u)throw Error("User not found"); socket.data.user=u; ctx.onlineUsers.set(String(u.userId),{socketId:socket.id,user:u}); cb&&cb({ok:true,user:u})}catch(e){cb&&cb({ok:false,error:e.message})}});
 socket.on("room:create",(p={},cb)=>{try{const u=user(socket)||p.user, r=ctx.engine.createRoom({name:p.name,host:u,settings:p.settings}); r.players[0].socketId=socket.id; socket.join(r.id); ctx.socketRooms.set(socket.id,r.id); cb&&cb({ok:true,room:ctx.engine.publicRoom(r,u.userId)}); ctx.engine.roomState(r)}catch(e){cb&&cb({ok:false,error:e.message})}});
 socket.on("room:join",(p={},cb)=>{try{const u=user(socket)||p.user, x=ctx.engine.joinRoom(p.roomId,u,socket.id,!!p.spectator); socket.join(x.room.id); ctx.socketRooms.set(socket.id,x.room.id); cb&&cb({ok:true,spectator:x.spectator,room:ctx.engine.publicRoom(x.room,u.userId)}); ctx.engine.roomState(x.room); ctx.engine.publishRooms()}catch(e){cb&&cb({ok:false,error:e.message})}});
 socket.on("room:settings",(p={},cb)=>{try{ctx.engine.updateSettings(roomOf(p.roomId),p.settings,user(socket)?.userId||p.userId); cb&&cb({ok:true})}catch(e){cb&&cb({ok:false,error:e.message})}});
 socket.on("game:start",(p={},cb)=>{try{ctx.engine.start(roomOf(p.roomId),user(socket)?.userId||p.userId); cb&&cb({ok:true})}catch(e){cb&&cb({ok:false,error:e.message})}});
 socket.on("game:next",async(p={},cb)=>{try{const r=roomOf(p.roomId); if(Number(r.hostUserId)!==Number(user(socket)?.userId))throw Error("Host only"); await ctx.engine.nextPhase(r); cb&&cb({ok:true})}catch(e){cb&&cb({ok:false,error:e.message})}});
 socket.on("game:nominate",(p={},cb)=>{try{cb&&cb(ctx.engine.nominate(roomOf(p.roomId),bySocket(roomOf(p.roomId),socket.id),p.targetId))}catch(e){cb&&cb({ok:false,error:e.message})}});
 socket.on("game:vote",(p={},cb)=>{try{cb&&cb(ctx.engine.vote(roomOf(p.roomId),bySocket(roomOf(p.roomId),socket.id),p.targetId))}catch(e){cb&&cb({ok:false,error:e.message})}});
 socket.on("game:action",(p={},cb)=>{try{cb&&cb(ctx.engine.action(roomOf(p.roomId),bySocket(roomOf(p.roomId),socket.id),p))}catch(e){cb&&cb({ok:false,error:e.message})}});
 socket.on("chat:send",(p={},cb)=>{try{const r=roomOf(p.roomId); if(!r)throw Error("Room not found"); const pl=bySocket(r,socket.id), sp=r.spectators.find(s=>s.socketId===socket.id), sender=pl||sp||user(socket), ch=p.channel==="mafia"?"mafia":"room"; if(ch==="mafia"&&(!pl||pl.team!=="mafia"||r.phase!=="night"))throw Error("Mafia chat only at night"); const msg=ctx.engine.chat(r,sender,p.message,ch); if(ch==="mafia")r.players.filter(x=>x.team==="mafia"&&x.socketId).forEach(x=>io.to(x.socketId).emit("chat:message",msg)); else io.to(r.id).emit("chat:message",msg); cb&&cb({ok:true,msg})}catch(e){cb&&cb({ok:false,error:e.message})}});
 socket.on("media:state",p=>{const r=roomOf(p.roomId), pl=bySocket(r,socket.id); if(!pl)return; ["micOn","cameraOn","speaking"].forEach(k=>{if(typeof p[k]==="boolean")pl[k]=p[k]}); ctx.engine.roomState(r)});
 socket.on("signal:offer",({to,signal})=>to&&signal&&io.to(to).emit("signal:offer",{from:socket.id,signal})); socket.on("signal:answer",({to,signal})=>to&&signal&&io.to(to).emit("signal:answer",{from:socket.id,signal})); socket.on("signal:ice",({to,candidate})=>to&&candidate&&io.to(to).emit("signal:ice",{from:socket.id,candidate}));
 socket.on("disconnect",()=>{const u=user(socket); if(u)ctx.onlineUsers.delete(String(u.userId)); ctx.engine.leave(socket.id); ctx.socketRooms.delete(socket.id)});
});
setInterval(async()=>{for(const r of ctx.rooms.values())if(!["waiting","ended"].includes(r.phase)){r.timer=Math.max(0,Number(r.timer||0)-1); if(r.timer<=0)await ctx.engine.nextPhase(r); else ctx.engine.roomState(r)}},1000)}
module.exports={attachSocketServer};
