name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy server
        run: railway up --detach --service 226d60e0-8aee-42f4-83b3-2151ee30dced
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: 08c2a0d2-1c54-4c07-8497-8130c7baa696

      - name: Deploy client
        run: railway up --detach --service 958a7cd3-adc4-49ad-a955-27c6df5794d8
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: 08c2a0d2-1c54-4c07-8497-8130c7baa696
